// Generates Web/public/css/themes.css from the shared EditorColorTheme.
//
// The palettes were transcribed from kirupa.com once, into Swift. Rather than
// transcribing them a second time into CSS — and letting the two drift — this
// compiles the real EditorColorTheme and prints what it computes. That matters
// most for the derived values: the 55% light-mode sidebar blend, the secondary
// text blend, and the black-or-white selection text chosen by WCAG contrast.
//
// Requires macOS, because the shared blend defers to NSColor there. It is only
// needed when the palettes change:
//
//     swiftc -O -o /tmp/generate-theme-css \
//         Web/tools/generate-theme-css.swift \
//         Shared/Sources/MarkdownEditorUI/EditorColorTheme.swift \
//         Shared/Sources/MarkdownEditorUI/PlatformTypes.swift
//     /tmp/generate-theme-css > Web/public/css/themes.css
//
// The generated file is committed, so serving the app never needs a toolchain.

import AppKit

func hexComponents(_ color: NSColor) -> (Int, Int, Int, CGFloat) {
    guard let srgb = color.usingColorSpace(.sRGB) else { return (0, 0, 0, 1) }
    return (
        Int((srgb.redComponent * 255).rounded()),
        Int((srgb.greenComponent * 255).rounded()),
        Int((srgb.blueComponent * 255).rounded()),
        srgb.alphaComponent
    )
}

func css(_ color: NSColor) -> String {
    let (red, green, blue, alpha) = hexComponents(color)
    if alpha >= 0.999 {
        return String(format: "#%02x%02x%02x", red, green, blue)
    }
    let rounded = (alpha * 1000).rounded() / 1000
    return "rgba(\(red), \(green), \(blue), \(rounded))"
}

func variables(for theme: EditorColorTheme) -> [(String, String)] {
    [
        ("page-background", css(theme.editorBackgroundColor)),
        ("canvas-background", css(theme.canvasBackgroundColor)),
        ("sidebar-background", css(theme.sidebarBackgroundColor)),
        ("primary-text", css(theme.primaryTextColor)),
        ("secondary-text", css(theme.secondaryTextColor)),
        ("separator", css(theme.separatorColor)),
        ("accent", css(theme.accentColor)),
        ("selection-background", css(theme.selectionBackgroundColor)),
        ("selection-text", css(theme.selectionTextColor)),
        ("inline-code-background", css(theme.inlineCodeBackgroundColor)),
        ("code-block-background", css(theme.codeBlockBackgroundColor))
    ]
}

func emit(_ selector: String, _ theme: EditorColorTheme) {
    print("\(selector) {")
    print("  color-scheme: \(theme.mode == .dark ? "dark" : "light");")
    for (name, value) in variables(for: theme) {
        print("  --me-\(name): \(value);")
    }
    print("}")
}

@main
enum ThemeCSSGenerator {
    static func main() {
        print("/* Generated by Web/tools/generate-theme-css.swift — do not edit by hand. */")
        print("/* Values originate in Shared/Sources/MarkdownEditorUI/EditorColorTheme.swift, */")
        print("/* which transcribes the theme selector on https://www.kirupa.com/. */")
        print("")

        print("/* Swatch fills and borders come from the site's #themeChooser rules and */")
        print("/* do not vary with the light/dark axis. */")
        print(":root {")
        for color in EditorThemeColor.allCases {
            print("  --me-swatch-\(color.rawValue): \(css(color.swatchFillColor));")
            print("  --me-swatch-\(color.rawValue)-border: \(css(color.swatchBorderColor));")
        }
        print("}")
        print("")

        emit(":root", EditorColorTheme(color: .blue, mode: .light))
        print("")

        for mode in EditorAppearanceMode.allCases {
            for color in EditorThemeColor.allCases {
                let theme = EditorColorTheme(color: color, mode: mode)
                // Not anchored to :root, so a nested element can carry a theme of
            // its own — which is how the Customize Theme popover previews a
            // draft without applying it to the app (PRD T-7).
            let selector =
                    "[data-theme-color=\"\(color.rawValue)\"]"
                    + "[data-appearance=\"\(mode.rawValue)\"]"
                emit(selector, theme)
                print("")
            }
        }
    }
}
